spring.application.name=backend

# Puerto
server.port=8080

# PostgreSQL de Render
spring.datasource.url=jdbc:postgresql://dpg-d946uq4vikkc73bnqlvg-a.ohio-postgres.render.com/ssu_ic32
spring.datasource.username=alejandrapacara

spring.datasource.password=VtIGMsnd7ayhy650LATnSPUl3W5P8Yo2

spring.datasource.driver-class-name=org.postgresql.Driver

# NUEVA LÍNEA: Forzar el dialecto de Postgres para evitar fallos de metadatos
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html